### ISSUE TITLE
Rain Passes Through Roof

### ISSUE THREAD

**Issue by QuestionableMemes** [buildthomas/Rain#1]
Hello, I'm writing this today to inquire about an issue I've been having with the rain script. Whenever I attempt to use the rain in an enclosed area, it passes through the roof as though it's not there. I've attempted to tweak the values without success, and I can't find any resources explaining how to fix it. If you could please respond to this, it would be greatly appreciated.

**Comment by buildthomas** [comment]
Hi, can you add a repro case? This is hard to investigate without.
