### ISSUE TITLE
RainStraight should use FacingCameraWorldUp

### ISSUE THREAD

**Issue by djfjfofoc3** [buildthomas/Rain#2]
The RainStraight Emitter should be using an Orientation of FacingCameraWorldUp, as to make it so, provided your camera is angled slightly up/down, but not enough to trigger RainTopDown, the rain still goes straight down, rather than at a slight angle.

Examples:

FacingCamera:
![image](https://user-images.githubusercontent.com/92001109/152921460-55b75c27-9eda-4668-acc9-4533e890cb3a.png)

FacingCameraWorldUp at that same camera angle:
![image](https://user-images.githubusercontent.com/92001109/152921492-652a0204-3dde-4334-801c-2d5f14b159ad.png)

It's a pretty small difference, but it's still noticable.

**Comment by buildthomas** [comment]
Thanks @MokiyCodes for the suggestion, looks much better! I'll update the DevForum topic and plugin accordingly.

**Comment by buildthomas** [comment]
I gave you a shout-out here: https://devforum.roblox.com/t/rain-module-plugin/157190/201?u=buildthomas (unfortunately I don't know your Roblox username)

**Comment by djfjfofoc3** [comment]
> Thanks @MokiyCodes for the suggestion, looks much better! I'll update the DevForum topic and plugin accordingly.

No problem, and I'm glad I could help improve the plugin.

> I gave you a shout-out here: https://devforum.roblox.com/t/rain-module-plugin/157190/201?u=buildthomas (unfortunately I don't know your Roblox username)

Thanks for the shout-out.
FYI it's [@MokiyRBX](https://www.roblox.com/users/137413810/profile) - you don't need to update your post unless you feel like doing such, however you can if you want.

**Comment by buildthomas** [comment]
> Thanks for the shout-out. FYI it's [@MokiyRBX](https://www.roblox.com/users/137413810/profile)

Updated! Thanks again.
